// <auto-generated />
using System;
using IntervencoesAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntervencoesAPI.Data.Migrations
{
    [DbContext(typeof(IntervencoesAPIContext))]
    [Migration("20260320164621_AddRelationshipsAndNullability")]
    partial class AddRelationshipsAndNullability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("IntervencoesAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CliCampo1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CliCampo2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CliCampo3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CliCampo4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataActualizacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDeInicio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NProcesso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdEntidade");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.Entidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Contribuinte")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataActualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("DesignacaoComercial")
                        .HasColumnType("TEXT");

                    b.Property<short?>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Item1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Item2")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item3")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Entidades");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.Intervencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccaoRealizada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Alerta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comentarios")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Coresponsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataConfirmacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataFimPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicioPrevista")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataLimite")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataQualidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EsforcoACobrar")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EsforcoReal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoricoEstados")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervencaoPaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoAlerta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrevisaoEsforco")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridade")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProcessoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TarefaAgendadaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TarefaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateUser")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Visibilidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProcessoId");

                    b.ToTable("Intervencaos");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.ProcessoProjecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvencaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPrevistaConclusao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EsforcoPrevisto")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EsforcoReal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fornecedores")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdContracto")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdProposta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumArquivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessoPaiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referencia")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsavel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("ProcessoProjectos");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.Cliente", b =>
                {
                    b.HasOne("IntervencoesAPI.Models.Entidade", "Entidade")
                        .WithMany("Clientes")
                        .HasForeignKey("IdEntidade")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.Intervencao", b =>
                {
                    b.HasOne("IntervencoesAPI.Models.ProcessoProjecto", "ProcessoProjecto")
                        .WithMany("Intervencaos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessoProjecto");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.ProcessoProjecto", b =>
                {
                    b.HasOne("IntervencoesAPI.Models.Cliente", "Cliente")
                        .WithMany("ProcessoProjectos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.Cliente", b =>
                {
                    b.Navigation("ProcessoProjectos");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.Entidade", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("IntervencoesAPI.Models.ProcessoProjecto", b =>
                {
                    b.Navigation("Intervencaos");
                });
#pragma warning restore 612, 618
        }
    }
}
